site_name: rainbow-connection
site_url: https://zkbt.github.com/rainbow-connection
nav:
    - index.md
    - installation.ipynb
    - light-sources.ipynb
    - stars.ipynb
    - atmospheres.ipynb
    - sunsets.ipynb
   # - api.md
theme:
  name: "material"
  features:
      - navigation.tracking
repo_url: https://github.com/zkbt/rainbow-connection/
plugins:
  - search
  - mkdocs-jupyter:
      execute : True
      include_source : True
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: "numpy"
          rendering:
            show_source: False
      custom_templates: templates
      watch:
        - rainbowconnection
  - exclude:
      glob:
        - "examples/*"
        - "*.pdf"
        - "notebooks/*"
        - "api.md"

# this is super borrowed from Christina Hedges' fabulous
# https://christinahedges.github.io/astronomy_workflow/
